
`cassandra-stress user no-warmup profile=file:///home/lucas/stress_tw_ttl_1h_1min.yaml ops\(insert=90,devdat=4,onerow=3,avgdat=3\) truncate=once n=2000000 -rate threads=24 -node rt1,rt2 -graph file=/home/lucas/graficos/grafico_TW.html title=TW_TTL_1H revision=sim_1m -log file=/home/lucas/resultados_stress/TW_TTL1H/time_window_iotbds_1min.log interval=30s`  
`sleep 30`                                                                                                                                                                                                                       
`cassandra-stress user no-warmup profile=file:///home/lucas/stress_tw_ttl_1h_50min.yaml ops\(insert=90,devdat=4,onerow=3,avgdat=3\) truncate=once n=2000000 -rate threads=24 -node rt1,rt2 -graph file=/home/lucas/graficos/grafico_TW.html title=TW_TTL_1H revision=sim_50m -log file=/home/lucas/resultados_stress/TW_TTL1H/time_window_iotbds_50min.log interval=30s`
`sleep 30`                                                                                                                                                                                                                       
`cassandra-stress user no-warmup profile=file:///home/lucas/stress_tw_ttl_1h_60min.yaml ops\(insert=90,devdat=4,onerow=3,avgdat=3\) truncate=once n=2000000 -rate threads=24 -node rt1,rt2 -graph file=/home/lucas/graficos/grafico_TW.html title=TW_TTL_1H revision=sim_60m -log file=/home/lucas/resultados_stress/TW_TTL1H/time_window_iotbds_60min.log interval=30s`
`sleep 30`                                                                                                                                                                                                                       
`cassandra-stress user no-warmup profile=file:///home/lucas/stress_tw_ttl_1h_180min.yaml ops\(insert=90,devdat=4,onerow=3,avgdat=3\) truncate=once n=2000000 -rate threads=24 -node rt1,rt2 -graph file=/home/lucas/graficos/grafico_TW.html title=TW_TTL_1H revision=sim_180m -log file=/home/lucas/resultados_stress/TW_TTL1H/time_window_iotbds_180min.log interval=30s`
`sleep 30`                                                                                                                                                                                                                       
`cassandra-stress user no-warmup profile=file:///home/lucas/stress_tw_ttl_1h_240min.yaml ops\(insert=90,devdat=4,onerow=3,avgdat=3\) truncate=once n=2000000 -rate threads=24 -node rt1,rt2 -graph file=/home/lucas/graficos/grafico_TW.html title=TW_TTL_1H revision=sim_240m -log file=/home/lucas/resultados_stress/TW_TTL1H/time_window_iotbds_240min.log interval=30s`
`sleep 30`                                                                                                                                                                                                                       
`cassandra-stress user no-warmup profile=file:///home/lucas/stress_tw_ttl1h_noCompaction.yaml ops\(insert=90,devdat=4,onerow=3,avgdat=3\) truncate=once n=2000000 -rate threads=24 -node rt1,rt2 -graph file=/home/lucas/graficos/grafico_TW.html title=TW_TTL_1H revision=sim_noCompact -log file=/home/lucas/resultados_stress/TW_TTL1H/time_window_iotbds_noCompact.log interval=30s`
